/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

import java.util.Arrays;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertNotNull;

public class AppTest {

   App classUnderTest;

   @Before public void initialize(){
      classUnderTest = new App();
   }

   @Test public void testAppHasAGreeting() {
      App classUnderTest = new App();
      assertNotNull("app should have a greeting", classUnderTest.getGreeting());
   }

   @Test public void should_display_HelloWorld(){
      Assert.assertEquals("Hello world.", classUnderTest.getGreeting());
   }

   @Test public void should_comparable_sort_number_correctly(){
         final int[] numbers = {-3, -5, 1, 7, 4, -2};
         final int[] expected = {-5, -3, -2, 1, 4, 7};

         Arrays.sort(numbers);
         assertArrayEquals(expected, numbers);
   }

   @Test public void should_sort_object_correctly(){
      final String[] strings = {"z", "x", "y", "abc", "zzz", "zazzy"};
      final String[] expected = {"abc", "x", "y", "z", "zazzy", "zzz"};

      Arrays.sort(strings);
      assertArrayEquals(expected, strings);
   }




}
